version: '3.8'

services:
    # PostgreSQL Database (for Account service)
    postgres:
        image: postgres:latest
        container_name: postgres_jec
        environment:
            POSTGRES_USER: jec_admin
            POSTGRES_PASSWORD: jec_admin
            POSTGRES_DB: JEC
        expose:
            - '6543'
        ports:
            - '6543:6543'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        command: -p 6543
        
    redis:
        image: redis:latest
        ports:
          - "6379:6379"
    
volumes:
    postgres_data: